/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */

export type BookmarkListResponseDtoPharmacy = {
  id?: number;
  name?: string;
  phone?: string;
  address?: string;
  monday?: string;
  tuesday?: string;
  wednesday?: string;
  thursday?: string;
  friday?: string;
  saturday?: string;
  sunday?: string;
  holiday?: string;
};
