/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */
import type { BookmarkGetResponseDtoBookmark } from "./bookmarkGetResponseDtoBookmark";

export interface BookmarkGetResponseDto {
  bookmark: BookmarkGetResponseDtoBookmark;
  statusCode: number;
  message: string;
}
