/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */
import type { CreateUserResponseUser } from './createUserResponseUser';

export interface CreateUserResponse {
  statusCode: number;
  message: string;
  user: CreateUserResponseUser;
}
