/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */

export interface CreateUserDto {
  email: string;
  name: string;
  password: string;
  birth: string;
  phone: string;
}
