/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */
import type { FindPasswordResponseResult } from './findPasswordResponseResult';

export interface FindPasswordResponse {
  statusCode: number;
  message: string;
  result: FindPasswordResponseResult;
}
