/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */

export type GetAlarmSetResponseDtoAlarm = {
  minute?: number;
  hour?: number;
  vip?: number[];
  repeatTime?: number;
  pillName?: string;
};
