/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */

export interface GetAlarmSettingResponse {
  minute: number;
  hour: number;
  vip: number[];
  repeatTime: number;
  pillName: string;
}
