/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */
import type { GetMypageResponsePharmacyBookMark } from './getMypageResponsePharmacyBookMark';
import type { GetMypageResponsePillBookMark } from './getMypageResponsePillBookMark';

export interface GetMypageResponse {
  PharmacyBookMark: GetMypageResponsePharmacyBookMark;
  PillBookMark: GetMypageResponsePillBookMark;
}
