/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */
import type { PharmacyControllerPharmacySearchOption } from './pharmacyControllerPharmacySearchOption';

export type PharmacyControllerPharmacySearchParams = { option: PharmacyControllerPharmacySearchOption; keyword: string };
