/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */
import type { PharmacySearchResponse } from './pharmacySearchResponse';

export interface PharmacySearchResponseDto {
  statusCode: number;
  message: string;
  pharmacies: PharmacySearchResponse[];
}
