/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */
import type { PharmacySearchResponseDtoPharmaciesItem } from './pharmacySearchResponseDtoPharmaciesItem';

export interface PharmacySearchResponseDto {
  statusCode: number;
  message: string;
  pharmacies: PharmacySearchResponseDtoPharmaciesItem[];
}
