/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */

export type PharmacyControllerPharmacySearchOption = typeof PharmacyControllerPharmacySearchOption[keyof typeof PharmacyControllerPharmacySearchOption];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PharmacyControllerPharmacySearchOption = {
  name: 'name',
  address: 'address',
} as const;
