/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */
import type { PharmacyBookmarkListResponse } from './pharmacyBookmarkListResponse';

export interface PharmacyBookmarkListResponseDto {
  statusCode: number;
  message: string;
  lists: PharmacyBookmarkListResponse;
}
