/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */

export type PillResultResponseDtoResult = {
  title?: string;
  effect?: string;
  sideEffect?: string;
  company?: string;
  usage?: string;
  caution?: string;
  keep?: string;
  cautionContent?: string;
  interactionContent?: string;
};
