/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */
import type { RecapchaResponseRecaptchav2 } from './recapchaResponseRecaptchav2';

export interface RecapchaResponse {
  statusCode: number;
  message: string;
  recaptchav2: RecapchaResponseRecaptchav2;
}
