/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */

export interface SetAlarmDto {
  deviceToken: string;
  vip: number[];
  hour: number;
  minute: number;
  pillName: string;
  userName: string;
  repeatTime: number;
}
