/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */
import type { SigninResponseUser } from './signinResponseUser';

export interface SigninResponse {
  statusCode: number;
  message: string;
  user: SigninResponseUser;
}
