/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * WonderingPill API Docs
 * WonderingPill API description
 * OpenAPI spec version: 1.0.0
 */

export interface UserEntity {
  id: string;
  email: string;
  name: string;
  password: string;
  phone: string;
  provider: string;
  profileImg: string;
  isDeleted: boolean;
  birth: string;
  createdAt: string;
  updatedAt: string;
}
