color_label = { 0: 'brown',
                1: 'brown/yellow',
                2: 'black',
                3: 'yellow',
                4: 'yellow/white',
                5: 'purple',
                6: 'purple/pink',
                7: 'purple/white',
                8: 'pink',
                9: 'pink/white',
                10: 'red',
                11: 'red/yellow',
                12: 'red/orange',
                13: 'red/white',
                14: 'orange',
                15: 'orange/yellow',
                16: 'orange/white',
                17: 'green',
                18: 'green/yellow',
                19: 'green/white',
                20: 'transparent',
                21: 'blue',
                22: 'blue/yellow',
                23: 'blue/white',
                24: 'white',
                25: 'white/gray',
                26: 'gray',
                }