version: '3'
services:
  backend_server:
    image: ghcr.io/parksujeong74/wonderingpill-back:latest
    restart: 'on-failure'
    ports:
      - 5000:5000
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: wondering-redis
    ports:
      - 6379:6379
    restart: always
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./data/:/data
      - ./conf/redis.conf:/usr/local/conf/redis.conf
